/**
 * Workspace Shared Types — DTOs shared between API routes and UI components.
 *
 * These types are used by both server-side API handlers and client-side
 * workspace components. Extracted here to avoid coupling server code
 * to UI component files.
 */

// ---------------------------------------------------------------------------
// Case Narrative — used by narrative API and NarrativeBlock component
// ---------------------------------------------------------------------------

/** Structured case narrative generated by the narrative synthesis API. */
export interface CaseNarrative {
    /** Descriptive case title (e.g., "In re: Smith Custody Modification") */
    title: string;
    /** 2-3 sentence executive summary */
    overview: string;
    /** 5-10 most legally significant facts */
    keyFactsSummary: string[];
    /** Key timeline milestones in chronological order */
    timelineSummary: string[];
    /** Confirmed pattern descriptions (only those meeting threshold) */
    supportedPatternsSummary: string[];
    /** Gaps/issues the user should address */
    openQuestions: string[];
    /** Full written narrative (500-1500 words) */
    narrative: string;
}

/** Format a generated case narrative into readable workspace draft text. */
export function formatCaseNarrativeAsDraft(narrative: CaseNarrative): string {
    const sections = [
        narrative.overview && `Overview\n${narrative.overview}`,
        narrative.keyFactsSummary.length > 0 && `Key Facts\n${narrative.keyFactsSummary.map((item, index) => `${index + 1}. ${item}`).join('\n')}`,
        narrative.timelineSummary.length > 0 && `Timeline Summary\n${narrative.timelineSummary.map((item, index) => `${index + 1}. ${item}`).join('\n')}`,
        narrative.supportedPatternsSummary.length > 0 && `Supported Patterns\n${narrative.supportedPatternsSummary.map((item, index) => `${index + 1}. ${item}`).join('\n')}`,
        narrative.narrative && `Narrative\n${narrative.narrative}`,
        narrative.openQuestions.length > 0 && `Open Questions\n${narrative.openQuestions.map((item, index) => `${index + 1}. ${item}`).join('\n')}`,
    ];

    return sections.filter(Boolean).join('\n\n');
}

// ---------------------------------------------------------------------------
// Report Configuration — used by report API and GenerateReportModal
// ---------------------------------------------------------------------------

/** Report output format. */
export type OutputType = 'summary' | 'court_document' | 'both';

/** Report writing tone. */
export type ToneType = 'neutral_concise' | 'detailed_organized' | 'attorney_ready';

/** How to handle pattern analysis in the report. */
export type PatternHandling = 'include_supported' | 'exclude';
