/**
 * Workspace Shared Types — DTOs shared between API routes and UI components.
 *
 * These types are used by both server-side API handlers and client-side
 * workspace components. Extracted here to avoid coupling server code
 * to UI component files.
 */

// ---------------------------------------------------------------------------
// Case Narrative — used by narrative API and NarrativeBlock component
// ---------------------------------------------------------------------------

/** Structured case narrative generated by the narrative synthesis API. */
export interface CaseNarrative {
    /** Descriptive case title (e.g., "In re: Smith Custody Modification") */
    title: string;
    /** 2-3 sentence executive summary */
    overview: string;
    /** 5-10 most legally significant facts */
    keyFactsSummary: string[];
    /** Key timeline milestones in chronological order */
    timelineSummary: string[];
    /** Confirmed pattern descriptions (only those meeting threshold) */
    supportedPatternsSummary: string[];
    /** Gaps/issues the user should address */
    openQuestions: string[];
    /** Full written narrative (500-1500 words) */
    narrative: string;
}

// ---------------------------------------------------------------------------
// Report Configuration — used by report API and GenerateReportModal
// ---------------------------------------------------------------------------

/** Report output format. */
export type OutputType = 'summary' | 'court_document' | 'both';

/** Report writing tone. */
export type ToneType = 'neutral_concise' | 'detailed_organized' | 'attorney_ready';

/** How to handle pattern analysis in the report. */
export type PatternHandling = 'include_supported' | 'exclude';
