/**
 * Workspace Shared Types — DTOs shared between API routes and UI components.
 *
 * These types are used by both server-side API handlers and client-side
 * workspace components. Extracted here to avoid coupling server code
 * to UI component files.
 */

// ---------------------------------------------------------------------------
// Case Narrative — used by narrative API and NarrativeBlock component
// ---------------------------------------------------------------------------

/** Structured case narrative generated by the narrative synthesis API. */
export interface CaseNarrative {
    /** Descriptive case title (e.g., "In re: Smith Custody Modification") */
    title: string;
    /** 2-3 sentence executive summary */
    overview: string;
    /** 5-10 most legally significant facts */
    keyFactsSummary: string[];
    /** Key timeline milestones in chronological order */
    timelineSummary: string[];
    /** Confirmed pattern descriptions (only those meeting threshold) */
    supportedPatternsSummary: string[];
    /** Gaps/issues the user should address */
    openQuestions: string[];
    /** Full written narrative (500-1500 words) */
    narrative: string;
}

/** Normalize runtime list values so draft formatting cannot throw on malformed payloads. */
function normalizeNarrativeList(value: unknown): string[] {
    if (!Array.isArray(value)) return [];
    return value
        .filter((item): item is string => typeof item === 'string')
        .map(item => item.trim())
        .filter(Boolean);
}

/** Format a generated case narrative into readable workspace draft text. */
export function formatCaseNarrativeAsDraft(narrative: CaseNarrative): string {
    const overview = typeof narrative.overview === 'string' ? narrative.overview.trim() : '';
    const body = typeof narrative.narrative === 'string' ? narrative.narrative.trim() : '';
    const keyFacts = normalizeNarrativeList(narrative.keyFactsSummary);
    const timeline = normalizeNarrativeList(narrative.timelineSummary);
    const patterns = normalizeNarrativeList(narrative.supportedPatternsSummary);
    const questions = normalizeNarrativeList(narrative.openQuestions);

    const sections = [
        overview && `Overview\n${overview}`,
        keyFacts.length > 0 && `Key Facts\n${keyFacts.map((item, index) => `${index + 1}. ${item}`).join('\n')}`,
        timeline.length > 0 && `Timeline Summary\n${timeline.map((item, index) => `${index + 1}. ${item}`).join('\n')}`,
        patterns.length > 0 && `Supported Patterns\n${patterns.map((item, index) => `${index + 1}. ${item}`).join('\n')}`,
        body && `Narrative\n${body}`,
        questions.length > 0 && `Open Questions\n${questions.map((item, index) => `${index + 1}. ${item}`).join('\n')}`,
    ];

    return sections.filter(Boolean).join('\n\n');
}

// ---------------------------------------------------------------------------
// Report Configuration — used by report API and GenerateReportModal
// ---------------------------------------------------------------------------

/** Report output format. */
export type OutputType = 'summary' | 'court_document' | 'both';

/** Report writing tone. */
export type ToneType = 'neutral_concise' | 'detailed_organized' | 'attorney_ready';

/** How to handle pattern analysis in the report. */
export type PatternHandling = 'include_supported' | 'exclude';
