name: 'Setup Node Environment'
description: 'Setup Node.js and install dependencies. Checkout must happen before this action.'

inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '24.14.1'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm

    - run: npm ci
      shell: bash
