import type { ClauseRetrievalBucket } from '../retrievalPlan';

export const TEXAS_POSSESSION_BUCKET_QUERIES: Record<ClauseRetrievalBucket, string[]> = {
  controlling_specific_clause: [
    'Father\'s Day',
    'Mother\'s Day',
    'holiday possession',
    'holiday schedule',
    'summer possession',
    'extended summer',
    'Friday preceding Father\'s Day',
    'Monday after Father\'s Day',
  ],
  competing_general_clause: [
    'weekend possession',
    'regular weekend possession',
    'Thursday',
    'Friday holiday',
    'federal holiday',
    'state holiday',
    'local holiday',
    'student holiday',
    'teacher in-service',
    'teacher in service',
  ],
  exception_priority_language: [
    'except as otherwise expressly provided',
    'except as otherwise provided',
    'notwithstanding',
    'subject to',
    'supersede conflicting',
    'controls over',
    'in the event of conflict',
  ],
  later_modification_language: [
    'modified order',
    'amended order',
    'later signed order',
    'this order supersedes',
    'except as modified',
    'prior order',
    'previous order',
  ],
  definition_language: [
    'definitions',
    'school',
    'student holiday',
    'teacher in-service',
    'teacher in service',
    'federal holiday',
    'state holiday',
    'local holiday',
    'weekend',
  ],
};

export const TEXAS_POSSESSION_ISSUE_TERMS = [
  'father\'s day',
  'fathers day',
  'mother\'s day',
  'mothers day',
  'holiday possession',
  'holiday schedule',
  'weekend possession',
  'student holiday',
  'teacher in-service',
  'teacher in service',
  'spring break',
  'thanksgiving',
  'christmas',
  'summer possession',
  'extended summer',
  'thursday',
  'friday',
];
