export const FILING_READINESS_CHECKLIST = [
  'court name',
  'cause number',
  'party names and roles',
  'document title',
  'filing or response deadline',
  'hearing date, if any',
  'what the other party is asking for',
  'current order',
  'facts in date order',
  'exhibits or exhibit list',
  'requested relief',
  'certificate of service',
  'signature block',
  'contact information',
  'local formatting and service rules',
  'whether notarization or verification is required',
  'filing fee or fee-waiver paperwork',
];
